### PR TITLE
Fix bug in remove_prefix and add a test case

### LINKED ISSUE #22: Bug in remove_prefix?
The following test seems to produce wrong result:
``` rust
#[test]
fn remove_prefix() {
    let mut trie = Trie::new();
    for i in 0..10 {
        let mut bytes = [0; 16];
        let (left, right) = bytes.split_at_mut(8);
        left.copy_from_slice(&u64::to_be_bytes(i));
        right.copy_from_slice(&u64::to_be_bytes(i));
        println!("insert {:?}", bytes);
        trie.insert(bytes, ());
    }
    println!("trie = {:?}", trie);
    assert_eq!(trie.count(), 10);
    for i in 0..5 {
        let subtrie = trie.remove_prefix(&u64::to_be_bytes(i)[..]);
        println!("remove_prefix {} removed {}", i, subtrie.count());
    }
    println!("trie = {:?}", trie);
    assert_eq!(trie.count(), 5);
}
```
The output is:
```
running 1 test
test remove_prefix ... FAILED

failures:

---- remove_prefix stdout ----
test remove_prefix ... FAILED

failures:

---- remove_prefix stdout ----
insert [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
insert [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1]
insert [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2]
insert [0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 3]
insert [0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 4]
insert [0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 5]
insert [0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 6]
insert [0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 7]
insert [0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 8]
insert [0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 9]
trie = {[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]: (), [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1]: (), [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2]: (), [0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0
, 0, 0, 0, 0, 3]: (), [0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 4]: (), [0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 5]: (), [0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 6]: (), [0, 0, 0, 0, 0, 0,
 0, 7, 0, 0, 0, 0, 0, 0, 0, 7]: (), [0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 8]: (), [0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 9]: ()}
remove_prefix 0 removed 10
remove_prefix 1 removed 0
remove_prefix 2 removed 0
remove_prefix 3 removed 0
remove_prefix 4 removed 0
trie = {}
thread 'remove_prefix' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `5`', tests/lib.rs:317:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
There are at least two problems:
- Each remove_prefix should return a subtree that has only 1 element. But the first one says "removed 10", the rest says "0".
- After remove_prefix, the count is still 10 despite that all elements are removed.

### PR DESCRIPTION
**Pull request by ninegua**
This fixes #22

### CODE REVIEW

File: tests/lib.rs [hunk 1]
```diff
@@ -465,3 +465,21 @@ fn serialize_pathological_branching() {
 
     assert_eq!(deserialized, original);
 }
+
+#[test]
+fn remove_prefix() {
```
Comment (sdleffler) [inline tests/lib.rs:470]:
```suggestion
fn issue_22_regression_remove_prefix() {
```

Just documenting why this is here.

File: src/node.rs [hunk 2]
```diff
@@ -696,7 +696,7 @@ impl<K: Borrow<[u8]>, V> Node<K, V> {
                 // unsafe: same rationale.
                 if unsafe { root.as_ref().unchecked_unwrap().unwrap_branch_ref() }
                     
-                    .choice >= prefix.len()
+                    .choice <= prefix.len()
```
Comment (sdleffler) [inline src/node.rs:699]:
```suggestion
                    .choice >= prefix.len() * 2
```

This check is here to make sure we don't remove a node which deals with sequences shorter than the prefix we're searching for. The bug here looks like we're comparing an index which is counting nybbles (the node's `choice` field) against an index counting bytes (`prefix.len()`) so on my machine, this fixes all tests while changing the direction of the comparison breaks a doctest. :)
